# Generated by Django 5.2.4 on 2025-07-06 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_turn', models.IntegerField(default=1)),
                ('current_year', models.IntegerField(default=2024)),
                ('current_quarter', models.IntegerField(default=1)),
                ('elections_passed', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.FloatField(default=5.0)),
                ('tax_rate', models.FloatField(default=20.0)),
                ('government_spending', models.FloatField(default=25.0)),
                ('customs_duty', models.FloatField(default=5.0)),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('event_type', models.CharField(choices=[('natural_disaster', 'Природная катастрофа'), ('economic_crisis', 'Экономический кризис'), ('sanctions', 'Санкции/торговые ограничения'), ('international_conflict', 'Международный конфликт'), ('commodity_price_change', 'Изменение цен на сырье'), ('social_protest', 'Социальные протесты')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('gdp_impact', models.FloatField(default=0.0)),
                ('inflation_impact', models.FloatField(default=0.0)),
                ('unemployment_impact', models.FloatField(default=0.0)),
                ('rating_impact', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('parameters_data', models.JSONField()),
                ('indicators_data', models.JSONField()),
                ('events_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='game.gamesession')),
            ],
            options={
                'unique_together': {('game_session', 'turn')},
            },
        ),
        migrations.CreateModel(
            name='EconomicIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('gdp_growth', models.FloatField()),
                ('inflation', models.FloatField()),
                ('unemployment', models.FloatField()),
                ('investments', models.FloatField()),
                ('president_rating', models.FloatField()),
                ('public_mood', models.FloatField(default=50.0)),
                ('export_volume', models.FloatField(default=30.0)),
                ('import_volume', models.FloatField(default=25.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='game.gamesession')),
            ],
            options={
                'unique_together': {('game_session', 'turn')},
            },
        ),
    ]
