# Generated by Django 5.2.4 on 2025-07-06 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicindicators',
            name='gdp_absolute',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='budget_impact',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='population_impact',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='budget_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='demographic_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='production_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='social_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='defense_priority',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='education_priority',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='healthcare_priority',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='infrastructure_priority',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='social_priority',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='accumulated_reserves',
            field=models.FloatField(default=500.0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='budget',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='event_type',
            field=models.CharField(choices=[('natural_disaster', 'Природная катастрофа'), ('economic_crisis', 'Экономический кризис'), ('sanctions', 'Санкции/торговые ограничения'), ('international_conflict', 'Международный конфликт'), ('commodity_price_change', 'Изменение цен на сырье'), ('social_protest', 'Социальные протесты'), ('technology_breakthrough', 'Технологический прорыв'), ('demographic_change', 'Демографические изменения')], max_length=50),
        ),
        migrations.CreateModel(
            name='BudgetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('tax_revenue', models.FloatField()),
                ('customs_revenue', models.FloatField()),
                ('total_revenue', models.FloatField()),
                ('education_spending', models.FloatField()),
                ('healthcare_spending', models.FloatField()),
                ('defense_spending', models.FloatField()),
                ('infrastructure_spending', models.FloatField()),
                ('social_spending', models.FloatField()),
                ('total_spending', models.FloatField()),
                ('budget_balance', models.FloatField()),
                ('accumulated_reserves', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_data', to='game.gamesession')),
            ],
            options={
                'unique_together': {('game_session', 'turn')},
            },
        ),
        migrations.CreateModel(
            name='DemographicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('population', models.FloatField()),
                ('natural_growth', models.FloatField()),
                ('migration_growth', models.FloatField()),
                ('life_expectancy', models.FloatField()),
                ('gdp_per_capita', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_data', to='game.gamesession')),
            ],
            options={
                'unique_together': {('game_session', 'turn')},
            },
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('capital_stock', models.FloatField()),
                ('labor_force', models.FloatField()),
                ('technology_progress', models.FloatField()),
                ('capital_intensity', models.FloatField()),
                ('labor_productivity', models.FloatField()),
                ('savings_rate', models.FloatField()),
                ('depreciation_rate', models.FloatField()),
                ('capital_share', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_data', to='game.gamesession')),
            ],
            options={
                'unique_together': {('game_session', 'turn')},
            },
        ),
        migrations.CreateModel(
            name='SocialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('education_level', models.FloatField()),
                ('healthcare_quality', models.FloatField()),
                ('social_stability', models.FloatField()),
                ('income_inequality', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_data', to='game.gamesession')),
            ],
            options={
                'unique_together': {('game_session', 'turn')},
            },
        ),
    ]
