# Generated by Django 5.2.4 on 2025-07-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_economicindicators_gdp_absolute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdata',
            name='social_transfers',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='demographicdata',
            name='social_transfers_per_capita',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='economicindicators',
            name='gold_reserves',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='economicindicators',
            name='money_supply',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name='economicindicators',
            name='printing_press_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='economicindicators',
            name='refinance_rate',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='economicindicators',
            name='reserve_ratio',
            field=models.FloatField(default=0.1),
        ),
    ]
