# Generated by Django 5.2.4 on 2025-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_budgetdata_social_transfers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdata',
            name='external_debt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='budgetdata',
            name='gold_reserves',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='economicindicators',
            name='exchange_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='economicindicators',
            name='external_debt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='economicindicators',
            name='industry_output',
            field=models.FloatField(default=600.0),
        ),
        migrations.AddField(
            model_name='economicindicators',
            name='interest_rate',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='economicindicators',
            name='population',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='economicindicators',
            name='services_output',
            field=models.FloatField(default=400.0),
        ),
    ]
