# Generated by Django 5.2.4 on 2025-07-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_budgetdata_external_debt_budgetdata_gold_reserves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='model_type',
            field=models.CharField(default='enhanced', max_length=32),
        ),
    ]
